version: '2'
services:
    template_gateway-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/template_gateway/mongodb/:/data/db/
